import_from_git(
  url: 'git@github.com:marhas/fastlane_shared.git',
  path: 'fastlane/Fastfile_shared'
)

default_platform(:ios)

ENV["podspec"] = "UAWalkthrough.podspec"
ENV["repo"] = "UnbadPods"
ENV["xcodeproj"] = "Example/UAWalkthrough.xcodeproj"

platform :ios do

end
